### ISSUE TITLE
Documentation of EFC arguments for capacity credit calculations

### ISSUE THREAD

**Issue by MartySchwarz** [NREL/PRAS#10]
assess(EFC(**UB**,**CI**,**MW range**,DisreteNonParametric(**[list A]**,**[list b]**)), EUE or LOLE, Backcast(), NonSequentialNetworkFlow(1000),Minimal(),**original system**,**new system**)

**UB** = the upper bound on the capacity value, often the nameplate capacity of the new unit

**CI** = the first of two conditions that stop the iterative calculation. Sets the confidence interval. If the reliability metrics (EUE or LOLE) calculated for both the upper and lower firm capacity bound are statistically identical within the confidence interval, the calculation stops.

**MW range** = the second of two conditions that stop the iterative calculation. Sets an absolute MW difference. If the reliability metrics calculated for both the upper and lower firm capacity bound are within this difference, the calculation stops.

**list A** = the list of regions in which the calculation places equivalent firm capacity

**list B** = the proportion of firm capacity the calculation places in each region. Must add up to 1.

**Comment by GordStephen** [comment]
Closed in https://github.com/NREL/PRAS/commit/5e01da42deadbe1acec1a7a07af3abda09c38c51
