### ISSUE TITLE
Question: Is the vision for PRAS to be exclusively a research tool or also to be used in the ISO and utility environments?

### ISSUE THREAD

**Issue by glarange** [NREL/PRAS#41]
Hi, Gord
I'm an employee in the ISO-NE on the Resource Adequacy Team. Have begun trying to use PRAS for some research topics since I am also a graduate student. I am impressed that PRAS does Sequential MC. Would you say the vision/purpose of PRAS is eventually to be an open source modern scripting alternative to GE MARS that could be used in full-scale projects at ISOs?
Thanks for the great work!
Gui

**Comment by GordStephen** [comment]
Hi Gui - PRAS is intended for use in full-scale projects at NREL and with our partners. Others often find it useful as well, but I would leave it to those individuals/entities to decide for themselves whether they'd consider it a viable alternative to other tools. :)

**Comment by glarange** [comment]
Fair enough! I myself need to learn more to make that determination. But am a big of Julia-based software so will definitely continue to assess scalability and flexibility. Meanwhile, could you point me to a pubic large-scale implementation with multiple regions, generators, interfaces etc? I looked in the papers but couldn't find much on the PRAS implementations.

**Comment by GordStephen** [comment]
I think this has been answered elsewhere, but including it here too for completeness - the rts.pras file in the tests directory includes multiple regions, generators, interfaces, storage devices, etc. https://github.com/NREL/PRAS/blob/master/test/PRASBase/rts.pras
