### ISSUE TITLE
Working with HDF5 files 

### ISSUE THREAD

**Issue by glarange** [NREL/PRAS#48]
I'm trying to better understand the workflow of working with HDF5 files. Would it be possible to show how you write the 
`toymodel.pras`? Something along the lines of the Python (or Julia) code below. That way, I can adapt and start defining HDF5 files from scratch.
I realize the structure of the PRAS/HDF5 files is defined here (https://github.com/NREL/PRAS/blob/master/SystemModel_HDF5_spec.md, but still a toy model code would be very helpful.

Thanks again.
```
# Generate random data for recording
acc_1 = np.random.random(1000)
station_number_1 = '1'
# unix timestamp
start_time_1 = 1542000276
# time interval for recording
dt_1 = 0.04
location_1 = 'Berkeley'

acc_2 = np.random.random(500)
station_number_2 = '2'
start_time_2 = 1542000576
dt_2 = 0.01
location_2 = 'Oakland'
```
```
hf = h5py.File('station.hdf5', 'w')
hf['/acc/1/data'] = acc_1
hf['/acc/1/data'].attrs['dt'] = dt_1
hf['/acc/1/data'].attrs['start_time'] = start_time_1
hf['/acc/1/data'].attrs['location'] = location_1

hf['/acc/2/data'] = acc_2
hf['/acc/2/data'].attrs['dt'] = dt_2
hf['/acc/2/data'].attrs['start_time'] = start_time_2
hf['/acc/2/data'].attrs['location'] = location_2

hf['/gps/1/data'] = np.random.random(100)
hf['/gps/1/data'].attrs['dt'] = 60
hf['/gps/1/data'].attrs['start_time'] = 1542000000
hf['/gps/1/data'].attrs['location'] = 'San Francisco'
hf.close()

```

**Comment by GordStephen** [comment]
If possible I would recommend building the PRAS `SystemModel` directly in Julia and then using the `savemodel` function to write it out to HDF5 - that way you know your data is both in the right format and satisfies the data integrity checks (no negative probabilities, etc). That said, there are also some Python scripts floating around here to do this too, I'll see if I can find one to share.

**Comment by glarange** [comment]
Yes, could you share a Julia script of model build for the toymodel.pras? That way, I can just extend it to larger systems.

**Comment by GordStephen** [comment]
In Julia, we would usually just create the systems directly (like is done in the tests: https://github.com/NREL/PRAS/blob/master/test/testsystems.jl) and the call `savemodel` on the result. But @MartySchwarz provided this example of creating the HDF5 directly in Python (for a single-region system):

```python
 #Initialize h5.
systemmodel = h5py.File(out_fn_full,'w')
    
#Root attributes
systemmodel.attrs['pras_dataversion'] = 'v0.5.0'
systemmodel.attrs['energy_unit'] = 'MWh'
systemmodel.attrs['power_unit'] = 'MW'
systemmodel.attrs['start_timestamp'] = '2019-03-01T00:00:00+05:30'
systemmodel.attrs['timestep_count'] = 8760
systemmodel.attrs['timestep_length'] = 1
systemmodel.attrs['timestep_unit'] = 'h'
    
#Make datasets.
systemmodel.create_dataset('/regions/load', dtype = 'uint32', data = load)
systemmodel.create_dataset('/generators/capacity', dtype = 'uint32', data = gen_cap)
systemmodel.create_dataset('/generators/failureprobability', dtype = 'f8', data = gen_failureprob)
systemmodel.create_dataset('/generators/repairprobability', dtype = 'f8', data = gen_repairprob)
    
#Make core datasets.
region_core = np.array([(b'region 1',)], dtype=[('name', 'S64')])
systemmodel.create_dataset('/regions/_core', data = region_core)
generators_core = np.array([
       (b'Coal plant 1', b'Thermal', b'region 1'),
       (b'Coal plant 2', b'Thermal', b'region 1'),
       (b'NGCC 1', b'Thermal', b'region 1'),
       (b'NGCC 2', b'Thermal', b'region 1'),
       (b'NGCT 1', b'Thermal', b'region 1'),
       (b'NGCT 2', b'Thermal', b'region 1'),
       (b'Hydro plant', b'Hydro', b'region 1'),
       (b'Wind plant 1', b'Wind', b'region 1'),
       (b'Wind plant 2', b'Wind', b'region 1'),
       (b'PV plant 1', b'Wind', b'region 1'),
       (b'PV plant 2', b'PV', b'region 1')],
    dtype=[('name', 'S64'), ('category', 'S64'), ('region', 'S64')])
systemmodel.create_dataset('/generators/_core', data = generators_core)
    
systemmodel.close()
```

**Comment by glarange** [comment]
Thanks, @GordStephen  and @MartySchwarz . Just one question: Why do you have these when building the model in Julia?

```
test3_lole = 0.320951
test3_lole_r = [0.2, 0.255341]
test3_lole_t = [0.19, 0.130951]
test3_lole_rt = [0.1 0.1; 0.19 0.065341]

test3_eue = 3.179289
test3_eue_t = [1.94, 1.239289]
test3_eue_r = [1.581902, 1.597387]
test3_eue_rt = [0.8 0.781902; 1.14 0.457387]
```

**Comment by GordStephen** [comment]
Sorry for the slow reply here! But to answer your questions:

a) Yes, these are the hand-derived solutions we expect to see, and the tests check that the model produces the same values.
b) If you have one region and 11 generators, then yes, you would expect those dimensions. One subtlety is that Julia defines matrices column-by-column while Python/NumPy defaults to row-by-row, so in Python you may need to create the matrices transposed from what you expect to see in Julia.

**Comment by GordStephen** [comment]
Closing this for now, but feel free to reopen if you have further questions!

**Comment by glarange** [comment]
Thanks!
G
