### ISSUE TITLE
assess(sys, NonSequentialMonteCarlo(), Shortfall())

### ISSUE THREAD

**Issue by glarange** [NREL/PRAS#49]
Hi, Gord
Getting a bug on the NonSeqMC, I think. Not sure if it's my version of Julia, but here goes:

```
shortfall, = assess(sys, Convolution(), Shortfall())
eue_overall = EUE(shortfall)
lole_overall = LOLE(shortfall)
println(eue_overall)
println(lole_overall)
```
```
EUE = 0.00000 MWh/1440min
LOLE = 0.00000 event-(5min)/1440min
```

```
shortfall, = assess(sys, NonSequentialMonteCarlo(), Shortfall())
eue_overall = EUE(shortfall)
lole_overall = LOLE(shortfall)
println(eue_overall)
println(lole_overall)
```

```
UndefVarError: `NonSequentialMonteCarlo` not defined

Stacktrace:
 [1] top-level scope
   @ In[16]:1
```

**Comment by GordStephen** [comment]
Actually, this isn't an bug, we removed this method a while back because no one was using it - you may be the first person to ever notice! Generally storage is always something people want to model, so we decided it wasn't worth the extra complexity of maintaining this method any more.
